### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by ozky** [Ri0n/QtNote#78]
I try to build this against Mageia Cauldron qt5.6 but it fails with this error everytime.

`storage/ptfstorage.cpp:131:14: error: ”class QtNote::Note” has no member named ”save”
     return n.save();
              ^
Makefile:4869: recipe for target 'ptfstorage.o' failed
make[1]: *** [ptfstorage.o] Error 1
make[1]: Leaving directory '/home/ozky/qtnote/libqtnote'
Makefile:70: recipe for target 'sub-libqtnote-make_first' failed
make: *** [sub-libqtnote-make_first] Error 2`

**Comment by Ri0n** [comment]
yes. I've broken master branch and no spare time to fix it.
Please try stable branch.

I'll try to fix master next month

**Comment by ozky** [comment]
No it fails with different errors i think it's because Mageia have qt5.6 and stable version is from 2013,not compatible anymore with newer qt versions.

**Comment by Ri0n** [comment]
it's stable code https://github.com/Ri0n/QtNote/archive/stable.zip from 2016. It works great with Qt5.
I use it every day with KDE5

**Comment by ozky** [comment]
Hups i downloaded wrong sources of stable release,now it build fine no problem anymore.

**Comment by Ri0n** [comment]
good.
new version in master branch will be really nice ;-)

**Comment by Ri0n** [comment]
3.0.5 released, but still from stable branch. so just a bug fix release.
