### ISSUE TITLE
Trying to understand something about the plugin manager

### ISSUE THREAD

**Issue by hubuga** [Ri0n/QtNote#83]
I'm trying to study your code and I was wondering, on the PluginManager you have something called PluginFeature, what you meant with "FirtFeature" and "LastFeature"?

**Comment by Ri0n** [comment]
I definitely need better a keyboard :)
I think you just found a bug. A loop over flags is something very weird :-)
Probably it was unnoticed after last plugin manager refactoring.

You can take a look on plugin manager in QStarDict project. It's also mostly mine and seems to work well. The ideas are approximately the same.

**Comment by Ri0n** [comment]
But the idea was to find most suitable plugins for current environment considering plugins priority and status.

**Comment by Ri0n** [comment]
btw master branch currently is totally broken. I by accident have commited there some work in progress.
"stable" branch is still compilable.

**Comment by Ri0n** [comment]
typo and iterator are fixed
